name: EOS LightAPI Docker Image Build

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Git repository to pull from'
        required: true
        default: 'https://github.com/cc32d9/eosio_light_api.git'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: greymass/lightapi

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: latest

      - name: Log in to the Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./lightapi/
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            LIGHTAPI_REPOSITORY=${{ github.event.inputs.repo }}
